---
title: "BayesianCartPole"
author: "Monkie"
date: "10/29/2019"
output: pdf_document
---



```{r}
list.of.packages <- c("splines", "devtools", "shinystan", "rstan", "lmerTest")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(splines)
library(devtools)
library(shinystan)
library(rstan)
library(lmerTest)

rm(list = ls())
setwd("~/Desktop/GITHUB/cartpole/cartpole")
df = read.csv("cartpole.csv")
dfsym = df
df = rbind(df,dfsym)
dfsym[,2:5] = -dfsym[,2:5]
dfsym$Action = as.numeric(dfsym$Action==0)
df$FutCarPos = c(df$CartPos[-1],0)
df$FutCarVel = c(df$CartVelocity[-1],0)
df$FutPolAng = c(df$PoleAngle[-1],0)
df$FutPolVel = c(df$PoleVelocity[-1],0)

df = df[-(which(df$Step==0)[-1] - 1),]
df = df[-nobs(df),]
# df$FutPos[(which(df$Step==0)[-1] - 1)]
df$ChgCarPos = df$FutCarPos - df$CartPos
df$ChgCarVel = df$FutCarVel - df$CartVelocity
df$ChgPolAng = df$FutPolAng - df$PoleAngle
df$ChgPolVel = df$FutPolVel - df$PoleVelocity

# DISTIRBUTE THE DATA FRAME FOR EACH ACTION
df0 = df[which(df$Action==0),]
df1 = df[which(df$Action==1),]

# FIT LINEAR MODELS FOR ACTION 0
fit0CarPos = lm(FutCarPos ~ CartPos ,data = df0)
plot(df0$CartPos,df0$FutCarPos)
abline(fit0CarPos$coefficients,col="red")

fit0CarVel = lm(FutCarVel ~ CartVelocity ,data = df0)
plot(df0$CartVelocity,df0$FutCarVel)
abline(fit0CarVel$coefficients,col="red")

fit0PolAng = lm(FutPolAng ~ PoleAngle ,data = df0)
plot(df0$PoleAngle,df0$FutPolAng)
abline(fit0PolAng$coefficients,col="red")

fit0PolVel = lm(FutPolVel ~ PoleVelocity ,data = df0)
plot(df0$PoleVelocity,df0$FutPolVel)
abline(fit0PolVel$coefficients,col="red")

# FIT LINEAR MODELS FOR ACTION 1
fit1CarPos = lm(FutCarPos ~ CartPos ,data = df1)
fit1CarVel = lm(FutCarVel ~ CartVelocity ,data = df1)
fit1PolAng = lm(FutPolAng ~ PoleAngle ,data = df1)
fit1PolVel = lm(FutPolVel ~ PoleVelocity ,data = df1)

par(mfrow=c(2,2))
plot(df1$CartPos,df1$FutCarPos,xlab="Cart Position @ time t", ylab="Cart Position @ time t+1")
abline(fit1CarPos$coefficients,col="red",)
plot(df1$CartVelocity,df1$FutCarVel,xlab="Cart Velocity @ time t", ylab="Cart Velocity @ time t+1")
abline(fit1CarVel$coefficients,col="red")
plot(df1$PoleAngle,df1$FutPolAng,xlab="Pole Angle @ time t", ylab="Pole Angle @ time t+1")
abline(fit1PolAng$coefficients,col="red")
plot(df1$PoleVelocity,df1$FutPolVel,xlab="Pole Velocity @ time t", ylab="Pole Velocity @ time t+1")
abline(fit1PolVel$coefficients,col="red")

summary(fit0CarPos$coefficients)
summary(fit0CarVel$coefficients)
summary(fit0PolAng$coefficients)
summary(fit0PolVel$coefficients)

summary(fit1CarPos$coefficients)
summary(fit1CarVel$coefficients)
summary(fit1PolAng$coefficients)
summary(fit1PolVel$coefficients)

# Predict the changes
fit1CarPosDelta = lm(ChgCarPos ~ CartPos + CartVelocity + PoleAngle + PoleVelocity + I(CartPos^2) + I(CartVelocity^2) +I(PoleAngle^2) 
                     + I(PoleVelocity^2),data = df1)
fit1CarVelDelta = lm(ChgCarVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity + I(CartPos^2) + I(CartVelocity^2) +I(PoleAngle^2) 
                     + I(PoleVelocity^2),data = df1)
fit1PolAngDelta = lm(ChgPolAng ~ CartPos + CartVelocity + PoleAngle + PoleVelocity + I(CartPos^2) + I(CartVelocity^2) +I(PoleAngle^2) 
                     + I(PoleVelocity^2),data = df1)
fit1PolVelDelta = lm(ChgPolVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity + I(CartPos^2) + I(CartVelocity^2) +I(PoleAngle^2) 
                     + I(PoleVelocity^2),data = df1)
summary(fit1CarPosDelta)
summary(fit1CarVelDelta)
summary(fit1PolAngDelta)
summary(fit1PolVelDelta)
# par(mfrow=c(2,2))
# plot(df1$CartPos,df1$ChgCarPos,xlab="Cart Position @ time t", ylab="Cart Position @ time t+1")
# abline(fit1CarPosDelta$coefficients,col="red",)
# plot(df1$CartVelocity,df1$ChgCarVel,xlab="Cart Velocity @ time t", ylab="Cart Velocity @ time t+1")
# abline(fit1CarVelDelta$coefficients,col="red")
# plot(df1$PoleAngle,df1$ChgPolAng,xlab="Pole Angle @ time t", ylab="Pole Angle @ time t+1")
# abline(fit1PolAngDelta$coefficients,col="red")
# plot(df1$PoleVelocity,df1$ChgPolVel,xlab="Pole Velocity @ time t", ylab="Pole Velocity @ time t+1")
# abline(fit1PolVelDelta$coefficients,col="red")

fit = rbind(fit1CarPosDelta$coefficients,fit1CarVelDelta$coefficients,fit1PolAngDelta$coefficients,fit1PolVelDelta$coefficients)
write.csv(fit,"Linearfit1.csv")

# Predict the changes
fit0CarPosDelta = lm(ChgCarPos ~ CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df0)
fit0CarVelDelta = lm(ChgCarVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolAngDelta = lm(ChgPolAng ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolVelDelta = lm(ChgPolVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
# par(mfrow=c(2,2))
# plot(df0$CartPos,df0$ChgCarPos,xlab="Cart Position @ time t", ylab="Cart Position @ time t+1")
# abline(fit0CarPosDelta$coefficients,col="red",)
# plot(df0$CartVelocity,df0$ChgCarVel,xlab="Cart Velocity @ time t", ylab="Cart Velocity @ time t+1")
# abline(fit0CarVelDelta$coefficients,col="red")
# plot(df0$PoleAngle,df0$ChgPolAng,xlab="Pole Angle @ time t", ylab="Pole Angle @ time t+1")
# abline(fit0PolAngDelta$coefficients,col="red")
# plot(df0$PoleVelocity,df0$ChgPolVel,xlab="Pole Velocity @ time t", ylab="Pole Velocity @ time t+1")
# abline(fit0PolVelDelta$coefficients,col="red")

fit0 = rbind(fit0CarPosDelta$coefficients,fit0CarVelDelta$coefficients,fit0PolAngDelta$coefficients,fit0PolVelDelta$coefficients)
write.csv(fit0,"Linearfit0.csv")

# Maybe only the angle is required  


```

































Add some noise into the data
```{r}
df = read.csv("cartpole50.csv")

rCartPos = max(df$CartPos) - min(df$CartPos)
rCartVel = max(df$CartVelocity) - min(df$CartVelocity)
rPoleAng = max(df$PoleAngle) - min(df$PoleAngle)
rPoleVel = max(df$PoleVelocity) - min(df$PoleVelocity)

errCartPos= rnorm(nobs(df$Step), 0, rCartPos/20)
errCartVel = rnorm(nobs(df$Step), 0,  rCartVel/20)
errPoleAng = rnorm(nobs(df$Step), 0,  rPoleAng/20)
errPoleVel = rnorm(nobs(df$Step), 0,  rPoleVel/20)
```

redo process with errors
```{r}
df$CartPos = df$CartPos + errCartPos
df$CartVelocity = df$CartVelocity + errCartVel
df$PoleAngle = df$PoleAngle + errPoleAng
df$PoleVelocity = df$PoleVelocity + errPoleVel

df$FutCarPos = c(df$CartPos[-1],0)
df$FutCarVel = c(df$CartVelocity[-1],0)
df$FutPolAng = c(df$PoleAngle[-1],0)
df$FutPolVel = c(df$PoleVelocity[-1],0)

df = df[-(which(df$Step==0)[-1] - 1),]
df = df[-nobs(df),]
# df$FutPos[(which(df$Step==0)[-1] - 1)]

# DISTIRBUTE THE DATA FRAME FOR EACH ACTION
df0 = df[which(df$Action==0),]
df1 = df[which(df$Action==1),]

# FIT LINEAR MODELS FOR ACTION 0
fit0CarPos = lm(FutCarPos ~ CartPos ,data = df0)
plot(df0$CartPos,df0$FutCarPos)
abline(fit0CarPos$coefficients,col="red")

fit0CarVel = lm(FutCarVel ~ CartVelocity ,data = df0)
plot(df0$CartVelocity,df0$FutCarVel)
abline(fit0CarVel$coefficients,col="red")

fit0PolAng = lm(FutPolAng ~ PoleAngle ,data = df0)
plot(df0$PoleAngle,df0$FutPolAng)
abline(fit0PolAng$coefficients,col="red")

fit0PolVel = lm(FutPolVel ~ PoleVelocity ,data = df0)
plot(df0$PoleVelocity,df0$FutPolVel)
abline(fit0PolVel$coefficients,col="red")
# FIT LINEAR MODELS FOR ACTION 1
fit1CarPos = lm(FutCarPos ~ CartPos ,data = df1)
fit1CarVel = lm(FutCarVel ~ CartVelocity ,data = df1)
fit1PolAng = lm(FutPolAng ~ PoleAngle ,data = df1)
fit1PolVel = lm(FutPolVel ~ PoleVelocity ,data = df1)

par(mfrow=c(2,2))
plot(df1$CartPos,df1$FutCarPos,xlab="Cart Position @ time t", ylab="Cart Position @ time t+1")
abline(fit1CarPos$coefficients,col="red",)
plot(df1$CartVelocity,df1$FutCarVel,xlab="Cart Velocity @ time t", ylab="Cart Velocity @ time t+1")
abline(fit1CarVel$coefficients,col="red")
plot(df1$PoleAngle,df1$FutPolAng,xlab="Pole Angle @ time t", ylab="Pole Angle @ time t+1")
abline(fit1PolAng$coefficients,col="red")
plot(df1$PoleVelocity,df1$FutPolVel,xlab="Pole Velocity @ time t", ylab="Pole Velocity @ time t+1")
abline(fit1PolVel$coefficients,col="red")
```




