---
title: "SImplifiedMLR"
author: "Monkie"
date: "11/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
list.of.packages <- c("splines", "devtools", "shinystan", "rstan", "lmerTest","gdata","foreach")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(splines)
library(devtools)
library(shinystan)
library(rstan)
library(lmerTest)
library(gdata)
library(foreach) # For parallel programming purposes

rm(list = ls())
setwd("~/Desktop/GITHUB/cartpole/cartpole")
df = read.csv("cartpole50.csv") #df = read.csv("cartpole50.csv") or = read.csv("cartpole.csv")

#Create Penalty for dying 
df$Reward[which(df$Reward!=1)-1] = -200

# Create symmetric data
dfsym = df
dfsym[,2:5] = -dfsym[,2:5]
dfsym$Action = as.numeric(dfsym$Action==0)
# Combined symmetric data
df = rbind(df,dfsym)
# Make a variable called FutureCarPosition 
df$FutCarPos = c(df$CartPos[-1],0)
df$FutCarVel = c(df$CartVelocity[-1],0)
df$FutPolAng = c(df$PoleAngle[-1],0)
df$FutPolVel = c(df$PoleVelocity[-1],0)
# Remove the last row where there is no transition after than
df = df[-(which(df$Reward==0)),]
# df = df[-(which(df$Step==0)[-1] - 1),]
# df = df[-nobs(df),]

# Create variable change
df$ChgCarPos = df$FutCarPos - df$CartPos
df$ChgCarVel = df$FutCarVel - df$CartVelocity
df$ChgPolAng = df$FutPolAng - df$PoleAngle
df$ChgPolVel = df$FutPolVel - df$PoleVelocity
# DISTIRBUTE THE DATA FRAME FOR EACH ACTION
df0 = df[which(df$Action==0),]
df1 = df[which(df$Action==1),]
# Predict the changes
fit1CarPosDelta = lm(ChgCarPos ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1CarVelDelta = lm(ChgCarVel ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1PolAngDelta = lm(ChgPolAng ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1PolVelDelta = lm(ChgPolVel ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
summary(fit1CarPosDelta)
summary(fit1CarVelDelta)
summary(fit1PolAngDelta)
summary(fit1PolVelDelta)

fit = rbind(fit1CarPosDelta$coefficients,fit1CarVelDelta$coefficients,fit1PolAngDelta$coefficients,fit1PolVelDelta$coefficients)
# MAKE DIRECTORY AND WRITE FILE INTO IT.
dirname = "simplifiedMLR"
if (!dir.exists(dirname)){
  dir.create(dirname)
}
write.csv(fit,paste0(dirname,"/","Linearfit1.csv"))

# Predict the changes
fit0CarPosDelta = lm(ChgCarPos ~ CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df0)
fit0CarVelDelta = lm(ChgCarVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolAngDelta = lm(ChgPolAng ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolVelDelta = lm(ChgPolVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)


fit0 = rbind(fit0CarPosDelta$coefficients,fit0CarVelDelta$coefficients,fit0PolAngDelta$coefficients,fit0PolVelDelta$coefficients)
write.csv(fit0,paste0(dirname,"/","Linearfit0.csv"))
# Maybe only the angle is required //  considering everything is better. Only consider angle might result unwind result  
```


Save initial data
```{r}
dirname = "DATA"
if (!dir.exists(dirname)){
  dir.create(dirname)
}
write.csv(df,paste0(dirname,"/","data.csv"))
```




GENERATE DATA Implement Bayesian Simulation (Begin)
```{r}
gen_data = FALSE

if (gen_data){
dirname = "BayesMLR-V1"
if (!dir.exists(dirname)){
  dir.create(dirname)
}

stan_model = '
data {
    // Define input data in this block
    int n;  // Number of samples
    int m;  // Number of features
    matrix[n, m] features;
    vector[n] y;  // outcome
}
transformed data {
    // Modify / transform input data.
    // This block runs once.
}
parameters {
    // These are random parameters which we
    // want to estimate
    vector[m] beta;  // Coefficients
    real<lower=0> epsilon;  // Uncertainty / unexplained variance
}
transformed parameters {
    // Create quantities derived from the parameters.
    // ytras = log(y)
    // Runs on every evaluation of log-prob
}
model {
    // Define your model here!
    y ~ normal(features * beta , epsilon);
    
    // Equivalent to:
    // increment_log_prob(normal_log(y, features * beta, epsilon));
}
generated quantities {
    // Can use to simulate / predict using parameters
    // Runs once per MCMC step after warmup
}
'

# -------------------------------
# Feed in given known data Do it for action 0 first 
# -------------------------------
# SEPARATE THE FIT Y MULTIPLE TIME FOR EACH VARIABLES.

X = df0[,2:5]
X = cbind(X,1)
# i=12
# for (i in 12:15){
foreach (i=12:15) %do% {
  Y = df0[,i]   # 12
  # Include intercept
  num_data <- length(Y)
  num_feat <- ncol(X)
  # Fit Linear regression
  lin_reg = stan(model_code=stan_model,
                 model_name="MLR on cartpole",
                 data=list(n = num_data, 
                           m = num_feat, 
                           features = X, 
                           y  = Y), 
                 iter=10000, chains=4, 
                 warmup=5000,control = list(adapt_delta = 0.99))
  
  # extract posterior samples for each parameter
  # Recreate data
  fit1_samples = rstan::extract(lin_reg)
  # str(fit1_samples)
  A_sample = fit1_samples[[1]]
  colnames(A_sample) = c("CartPos" ,"CartVelocity"  ,"PoleAngle" ,"PoleVelocity" ,"CONSTANT")
  # Write CSV in R
  write.csv(A_sample, file = paste0(dirname,"/",colnames(df0)[i],"BayesFit0.csv")) # 12
  Error = fit1_samples[[2]]
  write.csv(Error, file = paste0(dirname,"/",colnames(df0)[i],"Bayes_err_Action0.csv"))
}
# -------------------------------
# Feed in given known data Do it for action 1  
# -------------------------------
# SEPARATE THE FIT Y MULTIPLE TIME FOR EACH VARIABLES.

X = df1[,2:5]
X = cbind(X,1)
# for (i in 12:15){
foreach (i=12:15) %do% {
  Y = df1[,i]   # 12
  # Include intercept
  num_data <- length(Y)
  num_feat <- ncol(X)
  # Fit Linear regression
  lin_reg = stan(model_code=stan_model,
                 model_name="MLR on cartpole",
                 data=list(n = num_data, 
                           m = num_feat, 
                           features = X, 
                           y  = Y), 
                 iter=10000, chains=4, 
                 warmup=5000)
  
  # extract posterior samples for each parameter
  # Recreate data
  fit1_samples = rstan::extract(lin_reg)
  # str(fit1_samples)
  A_sample = fit1_samples[[1]]
  colnames(A_sample) = c("CartPos" ,"CartVelocity"  ,"PoleAngle" ,"PoleVelocity" ,"CONSTANT")
  # Write CSV in R
  write.csv(A_sample, file = paste0(dirname,"/",colnames(df1)[i],"BayesFit1.csv")) # 12
  Error = fit1_samples[[2]]
  write.csv(Error, file = paste0(dirname,"/",colnames(df1)[i],"Bayes_err_Action1.csv"))
}

}
```




For POMDP we need to know the relationship between the pole angle and the rest of the variable then we will use the rest of the variable to estimate the possible pole angle and do MDP on it.
```{r}
PoleAngleFit = lm(PoleAngle ~ CartVelocity + PoleVelocity ,data = df)#CartPos +
summary(PoleAngleFit)

plot(df$PoleVelocity,df$PoleAngle)
points(df$PoleVelocity,PoleAngleFit$fitted.values,col="red")
# plot(df$CartPos,df$PoleAngle)
# points(df$CartPos,PoleAngleFit$fitted.values,col="red")
plot(df$CartVelocity,df$PoleAngle)
points(df$CartVelocity,PoleAngleFit$fitted.values,col="red")

res = resid(PoleAngleFit)
plot(res,df$PoleAngle)
plot(res,df$CartVelocity)
# plot(res,df$CartPos)
plot(res,df$PoleVelocity)

hist(res)
dirname = "simplifiedMLR"
if (!dir.exists(dirname)){
  dir.create(dirname)
}

write.csv(PoleAngleFit$coefficients,paste0(dirname,"/","POMDPpoleangle.csv"))
```


GENERATE APPROXIMATE OF THE BAYES FOR POMDP

```{r}
gen_data = TRUE

if (gen_data){
dirname = "BayesMLR-V1"
if (!dir.exists(dirname)){
  dir.create(dirname)
}

stan_model = '
data {
    // Define input data in this block
    int n;  // Number of samples
    int m;  // Number of features
    matrix[n, m] features;
    vector[n] y;  // outcome
}
transformed data {
    // Modify / transform input data.
    // This block runs once.
}
parameters {
    // These are random parameters which we
    // want to estimate
    vector[m] beta;  // Coefficients
    real<lower=0> epsilon;  // Uncertainty / unexplained variance
}
transformed parameters {
    // Create quantities derived from the parameters.
    // ytras = log(y)
    // Runs on every evaluation of log-prob
}
model {
    // Define your model here!
    y ~ normal(features * beta , epsilon);
    
    // Equivalent to:
    // increment_log_prob(normal_log(y, features * beta, epsilon));
}
generated quantities {
    // Can use to simulate / predict using parameters
    // Runs once per MCMC step after warmup
}
'
# -------------------------------
# Feed in given known data and do it for the POLE ANGLE.
# -------------------------------
# SEPARATE THE FIT Y MULTIPLE TIME FOR EACH VARIABLES. # DONT NEED FOR LOOP, NEED TO CHANGE X AND Y THO.

X = df[,c(3,5)]
X = cbind(X,1)
# for (i in 12:15){

Y = df[,4]   # 12
# Include intercept
num_data <- length(Y)
num_feat <- ncol(X)
# Fit Linear regression
lin_reg = stan(model_code=stan_model,
               model_name="MLR on cartpole",
               data=list(n = num_data, 
                         m = num_feat, 
                         features = X, 
                         y  = Y), 
               iter=10000, chains=4, 
               warmup=5000)

# extract posterior samples for each parameter
# Recreate data
fit1_samples = rstan::extract(lin_reg)
# str(fit1_samples)
A_sample = fit1_samples[[1]]
colnames(A_sample) = c("CartVelocity","PoleVelocity" ,"CONSTANT")
# Write CSV in R
write.csv(A_sample, file = paste0(dirname,"/BayesPOMDPangle.csv")) # 12
Error = fit1_samples[[2]]
write.csv(Error, file = paste0(dirname,"/BayesPOMDP_err_angle.csv"))



}
```















