---
title: "SImplifiedMLR"
author: "Monkie"
date: "11/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
list.of.packages <- c("splines", "devtools", "shinystan", "rstan", "lmerTest")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(splines)
library(devtools)
library(shinystan)
library(rstan)
library(lmerTest)

rm(list = ls())
setwd("~/Desktop/GITHUB/cartpole/cartpole")
df = read.csv("cartpole50.csv") #df = read.csv("cartpole50.csv") or = read.csv("cartpole.csv")
# Create symmetric data
dfsym = df
dfsym[,2:5] = -dfsym[,2:5]
dfsym$Action = as.numeric(dfsym$Action==0)
# Combined symmetric data
df = rbind(df,dfsym)
# Make a variable called FutureCarPosition 
df$FutCarPos = c(df$CartPos[-1],0)
df$FutCarVel = c(df$CartVelocity[-1],0)
df$FutPolAng = c(df$PoleAngle[-1],0)
df$FutPolVel = c(df$PoleVelocity[-1],0)
# Remove the last row where there is no transition after than
df = df[-(which(df$Step==0)[-1] - 1),]
df = df[-nobs(df),]
# Create variable change
df$ChgCarPos = df$FutCarPos - df$CartPos
df$ChgCarVel = df$FutCarVel - df$CartVelocity
df$ChgPolAng = df$FutPolAng - df$PoleAngle
df$ChgPolVel = df$FutPolVel - df$PoleVelocity
# DISTIRBUTE THE DATA FRAME FOR EACH ACTION
df0 = df[which(df$Action==0),]
df1 = df[which(df$Action==1),]
# Predict the changes
fit1CarPosDelta = lm(ChgCarPos ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1CarVelDelta = lm(ChgCarVel ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1PolAngDelta = lm(ChgPolAng ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
fit1PolVelDelta = lm(ChgPolVel ~  CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df1)
summary(fit1CarPosDelta)
summary(fit1CarVelDelta)
summary(fit1PolAngDelta)
summary(fit1PolVelDelta)

fit = rbind(fit1CarPosDelta$coefficients,fit1CarVelDelta$coefficients,fit1PolAngDelta$coefficients,fit1PolVelDelta$coefficients)
write.csv(fit,"Linearfit1.csv")

# Predict the changes
fit0CarPosDelta = lm(ChgCarPos ~ CartPos + CartVelocity + PoleAngle + PoleVelocity,data = df0)
fit0CarVelDelta = lm(ChgCarVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolAngDelta = lm(ChgPolAng ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)
fit0PolVelDelta = lm(ChgPolVel ~ CartPos + CartVelocity + PoleAngle + PoleVelocity ,data = df0)


fit0 = rbind(fit0CarPosDelta$coefficients,fit0CarVelDelta$coefficients,fit0PolAngDelta$coefficients,fit0PolVelDelta$coefficients)
write.csv(fit0,"Linearfit0.csv")
# Maybe only the angle is required //  considering everything is better. Only consider angle might result unwind result  
```

Implement Bayesian Simulation
```{r}
stan_model = '
data {
    // Define input data in this block
    int n;  // Number of samples
    int m;  // Number of features
    matrix[n, m] features;
    vector[n] y;  // outcome
}
transformed data {
    // Modify / transform input data.
    // This block runs once.
}
parameters {
    // These are random parameters which we
    // want to estimate
    vector[m] beta;  // Coefficients
    real<lower=0> epsilon;  // Uncertainty / unexplained variance
}
transformed parameters {
    // Create quantities derived from the parameters.
    // ytras = log(y)
    // Runs on every evaluation of log-prob
}
model {
    // Define your model here!
    y ~ normal(features * beta , epsilon);
    
    // Equivalent to:
    // increment_log_prob(normal_log(y, features * beta, epsilon));
}
generated quantities {
    // Can use to simulate / predict using parameters
    // Runs once per MCMC step after warmup
}
'
# -------------------------------
# Feed in given known data Do it for action 0 first
# -------------------------------
X = df0[,2:5]
Y = df0[,12]
# Include intercept
X = cbind(X,1)
num_data <- length(Y)
num_feat <- ncol(X)
# Fit Linear regression
lin_reg = stan(model_code=stan_model,
               model_name="MLR on cartpole",
               data=list(n = num_data, 
                         m = num_feat, 
                         features = X, 
                         y  = Y), 
               iter=10000, chains=4, 
               warmup=5000)

# extract posterior samples for each parameter
# Recreate data
fit1_samples = rstan::extract(lin_reg)
# str(fit1_samples)
A_sample = fit1_samples[[1]]

# qplot(A_sample[,1],main = "lambda") 
# # Write CSV in R
# write.csv(A_sample[,1], file = "DamageM_Spray.csv")
# write.csv(A_sample[,2], file = "DamageC_Spray.csv")
# epsilon_Spray = fit1_samples[[2]]
# write.csv(epsilon_Spray, file = "DamageUnexplainable_Spray.csv")


```

